safe: true
timezone: Europe/Stockholm

title: What would Nobel do?
description: Nowhere in his last will did Alfred Nobel mention any prize in economics. For this simple reason, there is no Nobel Prize in Economic Sciences.
opengraph_description: There is no Nobel Prize in Economic Sciences. Nowhere in his last will did Alfred Nobel himself mention any such prize. It was in fact created by the Swedish Central Bank in 1968 – more than 70 years after Nobel’s death. The cleverly named “Prize in Economic Sciences in Memory of Alfred Nobel” was of course too much of a mouthful to avoid its obvious destiny of being shortened to a “Nobel Prize in Economics”.
tweet_text: There is no Nobel Prize in Economic Sciences.
live_url: http://whatwouldnobeldo.org
live_hostname: whatwouldnobeldo.org
email: info@whatwouldnobeldo.org
google_analytics_id: UA-44039901-1
