safe: true
timezone: Europe/Stockholm

title: What would Nobel do?
description: Nowhere in his last will did Alfred Nobel mention any prize in economics. For this simple reason, there is no Nobel Prize in Economic Sciences.
tweet_text: There is no Nobel Prize in Economic Sciences.
live_url: https://whatwouldnobeldo.org
live_hostname: whatwouldnobeldo.org
email: info@whatwouldnobeldo.org
google_analytics_id: UA-44039901-1
